name: family_planner
description: Семейный планер с синхронизацией задач
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  line_awesome_flutter: ^3.0.1
  lottie: ^3.3.2
  flutter_svg: ^2.2.1
  url_launcher: ^6.3.2

  # Supabase
  supabase_flutter: ^2.0.0

  # State Management
  provider: ^6.1.1

  # UI
  google_fonts: ^6.1.0
  intl: ^0.19.0

  # Icons
  cupertino_icons: ^1.0.6

  # HTTP для GigaChat API
  http: ^1.5.0

  gigachat_dart: ^0.1.2
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/icons/account.svg
    - assets/icons/family.svg
    - assets/icons/hat.svg
    - assets/icons/home.svg
    - assets/images/about-us.svg
    - assets/images/change-settings.svg
    - assets/images/designer-working.svg
    - assets/images/enter-your-password.svg
    - assets/images/free-shipping.svg
    - assets/images/magistrcoda/magistrcoda1.jpeg
    - assets/images/magistrcoda/magistrcoda2.webp
    - assets/images/magistrcoda/magistrcoda3.jpg
    - assets/images/magistrcoda/magistrcoda5.jpg
    - assets/images/magistrcoda/magistrcoda6.jpg
    - assets/animations/loading.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon4.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFD8BE"
  image: null
  color_dark: "#FFD8BE"
  android: true
  android_12:
    color: "#FFD8BE"
  ios: true
  web: false
  fullscreen: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill